# Generated by Django 2.0.4 on 2019-03-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='topping',
            name='unit',
            field=models.CharField(choices=[('cal', 'cal'), ('kcal', 'kcal')], default=0.0, max_length=5, verbose_name='Unidades'),
        ),
    ]
